Roll back numpy version in order to avoid error due to unknown numpy function.
  File "/anaconda3/envs/whakaari_env/lib/python3.7/site-packages/matplotlib/transforms.py", line 2819, in nonsingular
    if (not np.isfinite(vmin)) or (not np.isfinite(vmax)):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''